name: AWS OIDC

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        id: set-vars
        run: echo "ASSUME_ROLE=${{ secrets.AWS_ROLE_ARN }}" >> $GITHUB_ENV

      - name: Debug Variables
        run: echo "ASSUME_ROLE=${{ env.ASSUME_ROLE }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.ASSUME_ROLE }}

      - name: Print Hello World plan
        run: echo "Hello, Plan"

      - name: AWS CLI
        run: aws s3 ls
        
